cats99_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

end

cats99_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99_app/app/models/cat.rb
require 'date'

# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = ['brown', 'tabby', 'bengal', 'savannah']

  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w(M F) }
  validates :color, :sex, :color, :birth_date, :name, :description, presence: true

  def age
    ((DateTime.now.to_date - self.birth_date).to_i) / 365
  end

  def self.colors
    COLORS
  end

end

cats99_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats99_app/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    # debugger
    @colors = Cat::COLORS
    # @colors = cat.class.color
    render :new
  end

  def create
    cat = Cat.new(cat_params)

    if cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def edit
    @colors = Cat::COLORS
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :description, :color)
  end
end

cats99_app/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99_app/app/helpers/cats_helper.rb
module CatsHelper
end

cats99_app/app/views/cats/_form.html.erb
<%#= button_to "New", action: "create" %>
<% if action == :edit %>
  <% action_url =  %>


<form action="<%= cats_url %>" method="post">
  <input type='hidden' name = '_method' value = 'PATCH'

  <label for="name">Name</label>
  <input id="name" type="text" name='cat[name]' value="<%= @cat.name %>">

  <br>

  <label for="birth_date">birth_date</label>
  <input id="birth_date" type="date" name='cat[birth_date]' value="<%= @cat.birth_date %>">



  <br>
  <p>Please select cat's preferred pronouns</p>
    <input type="radio" id="M_input" name="cat[sex]" value="M">
    <label for="M_input">he/him/his</label>
  <br>
    <input type="radio" id="F_input" name="cat[sex]" value="F">
    <label for="F_input">she/her/hers</label>

  <br>
  <label for="color">Color</label>
  <select name='cat[color]'>
    <option>--please select--</option>
    <% @colors.each do |color| %>
      <option value="<%= color %>"><%= color %></option>
    <% end %>
  </select>

  <br>

  <label for="description">Description</label>
  <br>
  <textarea name="cat[description]">@cat.description</textarea>

  <input type="submit" value='Submit'>
</form>

cats99_app/app/views/cats/edit.html.erb
<h1> Improve your cat! </h1>

<%= render 'form', cat: @cat, action: :edit %>

cats99_app/app/views/cats/index.html.erb
<h1>  All of the Magical Cats </h1>

<% @cats.each do |cat| %>
<ul>
  <li><%= cat.name %></li>
  <li><%= link_to "Cat details", cat_url(cat) %></li>
</ul>
<% end %>

cats99_app/app/views/cats/new.html.erb
<h1> Build your cat! </h1>


<%#= button_to "New", action: "create" %>

<form action="<%= cats_url %>" method="post">

  <label for="name">Name</label>
  <input id="name" type="text" name='cat[name]'>

  <br>

  <label for="birth_date">birth_date</label>
  <input id="birth_date" type="date" name='cat[birth_date]'>



  <br>
  <p>Please select cat's preferred pronouns</p>
    <input type="radio" id="M_input" name="cat[sex]" value="M">
    <label for="M_input">he/him/his</label>
  <br>
    <input type="radio" id="F_input" name="cat[sex]" value="F">
    <label for="F_input">she/her/hers</label>

  <br>
  <label for="color">Color</label>
  <select name='cat[color]'>
    <option>--please select--</option>
    <% @colors.each do |color| %>
      <option value="<%= color %>"><%= color %></option>
    <% end %>
  </select>

  <br>

  <label for="description">Description</label>
  <br>
  <textarea name="cat[description]">Enter text here...</textarea>

  <input type="submit" value='Submit'>
</form>

cats99_app/app/views/cats/show.html.erb
<table>
  <colgroup span="4"></colgroup>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<%= link_to "All Da Cats", cats_url %>

cats99_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>